import type { Metadata } from "next";
import { SessionProvider } from "next-auth/react";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <SessionProvider>
        <body className={`flex flex-col min-h-svh`}>
          <main className="flex flex-col flex-1">{children}</main>
        </body>
      </SessionProvider>
    </html>
  );
}
